routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::prefix('/admin')->name('admin.')->namespace('App\Http\Controllers\Admin')->group(function(){
    Route::namespace('Auth')->group(function(){

        //Login Routes
        Route::get('/','LoginController@showLoginForm');
        Route::get('/login','LoginController@showLoginForm')->name('login');
        Route::post('/login','LoginController@login');
        Route::post('/logout','LoginController@logout')->name('logout');

    });

    Route::group(['middleware' => 'auth'], function() {
        Route::get('/dashboard','HomeController@index')->name('home');
        Route::get('/events', 'EventsController@index')->name('events');
        Route::get('/events/add', 'EventsController@add')->name('events.add');
        Route::post('/events/create', 'EventsController@create')->name('events.create');
        Route::get('/tickets', 'TicketController@index')->name('tickets');
    });
});

Route::group(['namespace' => 'App\Http\Controllers','middleware' => 'auth'], function() {
//Route::namespace('App\Http\Controllers')->group(function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/events', 'EventsController@index')->name('events');
    Route::get('/tickets', 'TicketController@index')->name('tickets');
    Route::get('/book/{id}', 'TicketController@book');
    Route::post('/ticket-booking', 'TicketController@ticketbooking')->name('ticketbooking');
});

app/Models/Events.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Events extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function tickets(){
        return $this->hasOne(Ticket::class,'event_id');
    }
}

app/Http/Controllers/Admin/EventsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Events;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class EventsController extends Controller
{
    public function index()
    {
        $events = Events::all();

        return view('admin.events.index', compact('events'));
    }

    public function add()
    {
        $events = Events::all();

        return view('admin.events.add', compact('events'));
    }

    public function create(Request $request)
    {
        $inputs = $request->all();
        $validator = Validator::make($inputs, [
            'title' => 'required|unique:events|max:255',
            'max_available_tickets' => 'required|integer',
            'start_time' => 'required|date_format:Y-m-d H:i:s|after:'.date("Y-m-d", strtotime('tomorrow')),
            'end_time' => 'required|date_format:Y-m-d H:i:s|after:start_time',
        ]);

        if ($validator->fails()) {
            return redirect('admin/events/add')
                ->withErrors($validator)
                ->withInput();
        }
        unset($inputs['_token']);

        $event = Events::create($inputs);

        return redirect()->route('admin.events');
    }
}

app/Http/Controllers/EventsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Events;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class EventsController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $events = Events::with(['tickets'=>function($q) use ($user){
            $q->where('user_id',$user->id);
        }])->get();

        return view('events', compact('events'));
    }
}

resources/views/admin/events/add.blade.php
@extends('admin.layouts.app')
@section('header')
    <link rel="stylesheet" type="text/css" media="screen"
          href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css" rel="stylesheet">

    <script type="text/javascript" src="//code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment-with-locales.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <style>

    </style>
@endsection
@section('content')
    <div class="container">
        @if ($errors->any())
            @foreach ($errors->all() as $error)
                <div class='error'>{{$error}}</div>
            @endforeach
        @endif
        <form method="post" action="{{route('admin.events.create')}}">
            @csrf
            <h2>Add Events</h2>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" placeholder="title" id="title" name="title" value="{{ old('title') }}">
                    </div>
                </div>
                <!--  col-md-6   -->

                <div class="col-md-6">
                    <div class="form-group">
                        <label for="max_available_tickets">Max Available Tickets</label>
                        <input type="number" class="form-control" placeholder="" id="max_available_tickets" name="max_available_tickets" value="{{ old('max_available_tickets') }}">
                    </div>


                </div>
            </div>


            <div class="row">
                <!--  col-md-6   -->
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="start_time">Start Time</label>
                        <input type="text" class="form-control" placeholder="Y-m-d H:i" id="start_time" name="start_time" value="{{ old('start_time') }}">
                    </div>
                </div>
            {{--<div style="overflow:hidden;">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-8">
                            <div id="datetimepicker12"></div>
                        </div>
                    </div>
                </div>
            </div>--}}
            <!--  col-md-6   -->

                <div class="col-md-6">
                    <div class="form-group">
                        <label for="end_time">End Time</label>
                        <input type="text" class="form-control" placeholder="Y-m-d H:i" id="end_time" name="end_time" value="{{ old('end_time') }}">
                    </div>
                </div>
                <!--  col-md-6   -->
            </div>
            <!--  row   -->

            <button type="submit" class="btn btn-primary">Submit</button>

        </form>
    </div>
@endsection
@section('footer')
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker12').datetimepicker({
                inline: true,
                sideBySide: true
            });
        });
    </script>
@endsection

resources/views/admin/events/index.blade.php
@extends('admin.layouts.app')
@section('header')
    <style>
        body {margin:2em;}
    </style>
@endsection
@section('content')
    <a class="btn btn-success" style="float:left;margin-right:20px;" href="{{ route('admin.events.add') }}">Add Events</a>
    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>Title</th>
            <th>Max Available Tickets</th>
            <th>Start Time</th>
            <th>End Time</th>
        </tr>
        </thead>
        <tbody>
        @foreach($events as $event)
            <tr>
                <td>{{$event->title}}</td>
                <td>{{$event->max_available_tickets}}</td>
                <td>{{$event->start_time}}</td>
                <td>{{$event->end_time}}</td>
            </tr>
        @endforeach
        @if($events->isEmpty())
            <tr>
                <td colspan="5">No record</td>
            </tr>
        @endif
        </tbody>
    </table>
@endsection
@section('footer')
    <script>
        $(document).ready(function() {
            //Only needed for the filename of export files.
            //Normally set in the title tag of your page.
            document.title='Simple DataTable';
            // DataTable initialisation
            $('#example').DataTable(
                {
                    "dom": '<"dt-buttons"Bf><"clear">lirtp',
                    "paging": true,
                    "autoWidth": true,
                    "buttons": [
                        'colvis',
                        'copyHtml5',
                        'csvHtml5',
                        'excelHtml5',
                        'pdfHtml5',
                        'print'
                    ]
                }
            );
        });
    </script>
@endsection